// <auto-generated />
using System;
using Aris.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Aris.Infrastructure.Migrations
{
    [DbContext(typeof(ArisDbContext))]
    [Migration("20260607234229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aris.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("EstufaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTUFA");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_RISCO");

                    b.HasKey("Id");

                    b.HasIndex("EstufaId");

                    b.ToTable("ALERTAS", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Cultura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CULTURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("EstufaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTUFA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EstufaId");

                    b.ToTable("CULTURAS", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Estufa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTUFA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ESTUFAS", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Irrigacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_IRRIGACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("EstufaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTUFA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("EstufaId");

                    b.ToTable("IRRIGACAO", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.LogAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ACAO");

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("LOG_ACOES", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.ParametroCultura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PARAMETRO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("CulturaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CULTURA");

                    b.Property<decimal?>("TempMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("TEMP_MAX");

                    b.Property<decimal?>("TempMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("TEMP_MIN");

                    b.Property<decimal?>("UmidadeMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("UMIDADE_MAX");

                    b.Property<decimal?>("UmidadeMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("UMIDADE_MIN");

                    b.HasKey("Id");

                    b.HasIndex("CulturaId")
                        .IsUnique();

                    b.ToTable("PARAMETROS_CULTURA", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("EstufaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTUFA");

                    b.Property<int>("TipoSensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("EstufaId");

                    b.HasIndex("TipoSensorId");

                    b.ToTable("SENSORES", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TELEMETRIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("TELEMETRIA", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.TipoSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE");

                    b.HasKey("Id");

                    b.ToTable("TIPOS_SENSOR", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("Aris.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Estufa", "Estufa")
                        .WithMany("Alertas")
                        .HasForeignKey("EstufaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estufa");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Cultura", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Estufa", "Estufa")
                        .WithMany("Culturas")
                        .HasForeignKey("EstufaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estufa");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Estufa", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Estufas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Irrigacao", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Estufa", "Estufa")
                        .WithMany("Irrigacoes")
                        .HasForeignKey("EstufaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estufa");
                });

            modelBuilder.Entity("Aris.Domain.Entities.ParametroCultura", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Cultura", "Cultura")
                        .WithOne("ParametroCultura")
                        .HasForeignKey("Aris.Domain.Entities.ParametroCultura", "CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultura");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Estufa", "Estufa")
                        .WithMany("Sensores")
                        .HasForeignKey("EstufaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aris.Domain.Entities.TipoSensor", "TipoSensor")
                        .WithMany("Sensores")
                        .HasForeignKey("TipoSensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estufa");

                    b.Navigation("TipoSensor");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Telemetria", b =>
                {
                    b.HasOne("Aris.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Telemetrias")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Cultura", b =>
                {
                    b.Navigation("ParametroCultura");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Estufa", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Culturas");

                    b.Navigation("Irrigacoes");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Telemetrias");
                });

            modelBuilder.Entity("Aris.Domain.Entities.TipoSensor", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Aris.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Estufas");
                });
#pragma warning restore 612, 618
        }
    }
}
